#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme

title: Personal Site
description: Personal Site 


#---
#date:   2020-04-15 15:19:23 -0700
#categories: docs & info
#---

#avatar: /_assets/img/favicon.ico
#theme_mode: dark

image: /_assets/img/favicon.ico

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

  syntax-highlighting:
      enabled : true
      css: /_sass/zenburn.css

    
  syntax_highlighter_opts:
      #Line Numbers
      span:
        line_numbers: false
      block:
        line_numbers: true
        start_line: 1

plugins: 
  - jekyll-avatar 
  - highlight-linedivs