#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme

title: Personal Site
description: Personal Site 


#---
#date:   2020-04-15 15:19:23 -0700
#categories: docs & info
#---

#avatar: /_assets/img/favicon.ico
#theme_mode: dark

image: /_assets/img/favicon.ico

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 math_engine: mathjax

 syntax_highlighter_opts:
  enabled : true
  css_class: /_sass/zenburn.css
#  line_numbers: true
#    #Line Numbers
#  span:
#    line_numbers: false
#  block:
#    line_numbers: true
#    start_line: 1


#syntax-highlighting:
#    enabled : true
#    #css: /_sass/zenburn.css

    


plugins: 
  - jekyll-avatar 