#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme

title: Personal Site
description: Personal Site 

#theme_mode: dark

image: /_assets/img/favicon.ico

markdown: kramdown
highlighter: rouge

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 math_engine: mathjax

#syntax-highlighting
# syntax_highlighter_opts:
#  enabled : true
#  css_class: 'highlight'
#  css_class: /_sass/zenburn.css
#  line_numbers: true
#    #Line Numbers
#  span:
#    line_numbers: false
#  block:
#    line_numbers: true
#   start_line: 1

plugins: 
  - jekyll-avatar 

## optional settings ##
meta:
  key1: value1
  key2: value2

google:
  gtag:
  adsense:
# also available via file: _include/assets/custom.scss
scss:
  .wy-nav-content-wrap{background:#fcfcfc}
  .wy-nav-content-wrap .wy-nav-content{max-width:none}
  
# also available via file: _include/assets/custom.js
script:

